live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
opacity = 0.95
blur = true
startup_mode = "Maximized"
dynamic_title = true
decorations_theme_variant = "Dark"

# TokyoNight Alacritty Colors
# Default colors
[colors.primary]
background = '#24283b'
foreground = '#c0caf5'

[font.normal]
family = "JetBrainsMonoNL Nerd Font"

#[colors.cursor]
#cursor = '#c0caf5'
#text = '#24283b'

# Normal colors
[colors.normal]
black = '#1d202f'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#a9b1d6'

# Bright colors
[colors.bright]
black = '#414868'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#c0caf5'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#ff9e64'

[[colors.indexed_colors]]
index = 17
color = '#db4b4b'
