# If you come from bash you might have to change your $PATH.
export GOPATH=${HOME}/projects/go
export PATH=${HOME}/bin:${GOPATH}/bin:/usr/local/bin:${HOME}/.cargo/bin:${PATH}

# Path to your oh-my-zsh installation.
export ZSH=${HOME}/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="afowler"

plugins=(archlinux bazel brew docker docker-compose genpass git golang helm kubectl kubectx rust ssh-agent systemadmin tmux vscode)

# Settings
export ZSH_TMUX_AUTOSTART=true

export LANG=en_US.UTF-8

export SSH_KEY_PATH="${HOME}/.ssh/rsa_id"

export HISTFILESIZE=1000000000
export HISTSIZE=1000000000

export EDITOR='nvim'
export MANPAGER='nvim +Man!'
export MANWIDTH=999

export GTK_THEME=Arc-Darker
export JAVA_HOME=/home/linuxbrew/.linuxbrew/Cellar/openjdk/21.0.3

export HOMEBREW_NO_ENV_HINTS=true

alias vim='nvim'

source ${HOME}/.local_env_zsh

# Load zsh to apply plugins and settings
source ${ZSH}/oh-my-zsh.sh

